// docs/metrics-plan.md phase 5, expanded in docs/metrics-phase/5-parity-tests.md: the
// four `§14` parity slots, plus a fifth for the segmentation item the original slots
// never covered.
//
// The pre-phase-5 version of this file was four placeholder bodies asserting a tolerance
// constant against itself (e.g. `expect(viewConfidenceTolerance, 0.01)`), permanently
// skipped with a stale "Needs concrete ML service" reason -- every capability service has
// had a real implementation since before phase 4. This version replaces all four with
// real native-vs-Python comparisons, gated on the phase 2 native harness exactly like
// functional_scenarios_test.dart's Tier B.
//
// Tolerances are read from test/fixtures/parity/tolerances.json, generated by
// `python -m ML.parity.compare` -- the single place they are defined (task 1). The golden
// values are read from test/fixtures/parity/expected.json, generated by
// `python -m ML.parity.run_reference` over the phase 3.1 scenario corpus
// (test/fixtures/scenarios/); regenerate both with those two commands (PowerShell, not
// Bash -- see docs/metrics-phase/5-parity-tests.md) after any manifest, model, or fixture
// change, and re-snapshot test/fixtures/scenarios/ first (it is untracked and
// generate_fixtures.py clobbers meta.json).
//
// What each leg actually measures, so a green run is not over-read:
//
//   view    -- genuinely end-to-end: the golden runs onnxruntime on the SAME shipped
//              assets/ml/view/model.onnx, independently of the native decode/resize/
//              inference path. Runs on every fixture (view always executes first).
//   health  -- also genuinely end-to-end, for the same reason. Only asserted on fixtures
//              whose LIVE envelope reports health.status == "ok" -- a view-rejected
//              fixture (05) never reaches the health stage on either side, and asserting
//              against a golden computed regardless of that would compare something the
//              native pipeline never produced.
//   weight  -- NOT independent of the native feature extraction: the golden was computed
//              by feeding the fixture's OWN previously-recorded feature values into
//              onnxruntime on the shipped xgboost.onnx (task 8's "hold the feature vector
//              equal" design). It therefore checks that the native pipeline's feature ->
//              ONNX wiring (capture, ordering, tensor shape) agrees with a second
//              onnxruntime embedding of the identical graph -- real coverage of a real
//              wiring class of bug, but not an independent XGBoost re-implementation.
//              That independent check does not exist in this repo (no training-time
//              `src/` package, and hand-writing one for this phase alone would be a
//              second unverified implementation). Export/quantization fidelity against
//              the ORIGINAL trained XGBoost model is a separate, already-covered check --
//              phase 6 asserts the manifest's own recorded `onnx_max_abs_diff`.
//   features -- the values comparison is deliberately NOT done per-scenario-fixture here:
//              the golden's `features` block is a copy of the SAME envelope's own
//              recorded values (there is no independent Python computation of features
//              from a photo without re-running segmentation, which is out of scope --
//              see the "segmentation" note below), so comparing it back would only prove
//              the native pipeline reproduces its own earlier output, not that it agrees
//              with Python. The genuine native-vs-Python feature parity is
//              ML/parity/chen16_feature_port_gate.py, run here as a subprocess against the
//              real ground-truth mask corpus (Instaham/PIGRGB-Weight/MASK_3394/), where
//              both sides start from the identical mask and no segmentation is needed.
//              What IS asserted per fixture is cheap and real: `features.order` equals
//              the manifest's declared order and `features.family` equals the manifest's
//              declared family (AGENTS.md rule 2, pinned on the native side), plus
//              `features.status` asserted as its observed value rather than papered over.
//   segmentation -- BLOCKED, not written. docs/metrics-phase/5-parity-tests.md's finding 1
//              plus this task's own investigation: an independent segmentation oracle
//              needs either the training-time `src/` package (not in this repo -- only
//              the deployed C++ port under model_and_cutter/ is) or a from-scratch Python
//              YOLO postprocessor (letterbox undo, NMS, proto-mask decode) with nothing to
//              verify it against. Writing the latter risks a second unverified
//              implementation and mislabelling its own bugs as native port bugs. The
//              honest fix is native-side mask export (subphase 5.1), recorded and
//              deliberately not taken here.
import 'dart:convert';
import 'dart:io';

import 'package:flutter_test/flutter_test.dart';

import '../support/native_harness.dart';

Map<String, dynamic> _readJson(String path) =>
    jsonDecode(File(path).readAsStringSync()) as Map<String, dynamic>;

final Map<String, dynamic> _tolerances = _readJson(
  'test/fixtures/parity/tolerances.json',
);
final Map<String, dynamic> _golden = _readJson(
  'test/fixtures/parity/expected.json',
);

double _tol(String key) => (_tolerances[key] as num).toDouble();

bool _absClose(num expected, num actual, double tol) =>
    (expected.toDouble() - actual.toDouble()).abs() <= tol;

/// Compares two class -> probability maps at an absolute tolerance, returning a
/// human-readable mismatch list (empty when they agree) rather than failing on the first
/// difference -- a parity failure should show every mismatching class at once.
List<String> _compareProbabilities(
  Map<String, dynamic> expected,
  Map<String, dynamic> actual,
  double tol,
) {
  final mismatches = <String>[];
  for (final entry in expected.entries) {
    final e = (entry.value as num).toDouble();
    final a = ((actual[entry.key] as num?) ?? 0.0).toDouble();
    if (!_absClose(e, a, tol)) {
      mismatches.add('${entry.key}: expected=$e actual=$a (abs tol $tol)');
    }
  }
  return mismatches;
}

/// Loads the manifest-declared weight feature family/order directly (AGENTS.md rule 2 --
/// never hardcode the feature list), mirroring what NativeHarness already reads for
/// `featureFamily`.
Map<String, dynamic> _readFeatureOrderAsset() =>
    _readJson('assets/ml/weight/feature_order.json');

/// Fixture directory names that have a golden in expected.json. Matches
/// test/support/scenario_fixture.dart's directory convention but iterates the parity
/// corpus directly, since parity's key is the fixture's directory name, not its §14
/// scenario id.
List<String> get _fixtureNames => _golden.keys.toList()..sort();

String _fixtureDir(String name) => 'test/fixtures/scenarios/$name';

Map<String, dynamic> _fixtureMeta(String name) =>
    _readJson('${_fixtureDir(name)}/meta.json');

double? _fixtureCmPerPixel(Map<String, dynamic> meta) {
  final ref = meta['reference'] as Map<String, dynamic>?;
  final endpoints = ref?['pixel_endpoints'] as Map<String, dynamic>?;
  return (endpoints?['cm_per_px'] as num?)?.toDouble();
}

/// Most fixtures carry a single `image_file`; scenario 11 (container-format coverage)
/// carries `image_files: {heic, jpeg, png}` instead (test/support/scenario_fixture.dart's
/// own convention). The golden in expected.json was generated against the jpeg variant
/// (ML/parity/run_reference.py looks for `image.jpg` -- the one container format every
/// platform this test runs on can decode without a HEIC codec), so this must match it.
String _fixtureImagePath(String name, Map<String, dynamic> meta) {
  final single = meta['image_file'] as String?;
  if (single != null) return '${_fixtureDir(name)}/$single';
  final variants = meta['image_files'] as Map<String, dynamic>;
  return '${_fixtureDir(name)}/${variants['jpeg']}';
}

void main() {
  group('Model-Parity Tests (§14)', () {
    for (final name in _fixtureNames) {
      final golden = _golden[name] as Map<String, dynamic>;
      final meta = _fixtureMeta(name);

      group('Fixture $name', () {
        test(
          'view probabilities parity against Python/onnxruntime reference',
          () {
            final load = NativeHarness.load();
            switch (load) {
              case NativeHarnessSkip(:final reason):
                markTestSkipped(reason);
                return;
              case NativeHarnessReady(:final harness):
                addTearDown(harness.dispose);
                final (_, envelope) = harness.run(
                  _fixtureImagePath(name, meta),
                  cmPerPixel: _fixtureCmPerPixel(meta),
                );
                final view = envelope['view'] as Map<String, dynamic>?;
                expect(
                  view?['status'],
                  'ok',
                  reason: 'view stage must run for every fixture',
                );
                final expectedProbs =
                    (golden['view'] as Map<String, dynamic>)['probabilities']
                        as Map<String, dynamic>;
                final actualProbs =
                    view!['probabilities'] as Map<String, dynamic>;
                final mismatches = _compareProbabilities(
                  expectedProbs,
                  actualProbs,
                  _tol('view_probability_abs'),
                );
                expect(
                  mismatches,
                  isEmpty,
                  reason:
                      'view probability mismatches for $name:\n'
                      '${mismatches.join('\n')}',
                );
            }
          },
        );

        test('health probabilities parity against Python/onnxruntime reference', () {
          final load = NativeHarness.load();
          switch (load) {
            case NativeHarnessSkip(:final reason):
              markTestSkipped(reason);
              return;
            case NativeHarnessReady(:final harness):
              addTearDown(harness.dispose);
              final (_, envelope) = harness.run(
                _fixtureImagePath(name, meta),
                cmPerPixel: _fixtureCmPerPixel(meta),
              );
              final health = envelope['health'] as Map<String, dynamic>?;
              if (health == null || health['status'] != 'ok') {
                // AGENTS.md rule 4: health is independent of the weight/view branch, but
                // a view-rejected fixture (e.g. 05_offdorsal_view) never reaches the
                // health stage at all on either side -- there is nothing to compare.
                markTestSkipped(
                  'health did not run for $name on this fixture '
                  '(status: ${health?['status']}) -- nothing to compare',
                );
                return;
              }
              final expectedProbs =
                  (golden['health'] as Map<String, dynamic>)['probabilities']
                      as Map<String, dynamic>;
              final actualProbs =
                  health['probabilities'] as Map<String, dynamic>;
              final mismatches = _compareProbabilities(
                expectedProbs,
                actualProbs,
                _tol('health_probability_abs'),
              );
              expect(
                mismatches,
                isEmpty,
                reason:
                    'health probability mismatches for $name:\n'
                    '${mismatches.join('\n')}',
              );
          }
        });

        test(
          'weight feature-order/family pinning + weight prediction wiring parity',
          () {
            final load = NativeHarness.load();
            switch (load) {
              case NativeHarnessSkip(:final reason):
                markTestSkipped(reason);
                return;
              case NativeHarnessReady(:final harness):
                addTearDown(harness.dispose);
                final (_, envelope) = harness.run(
                  _fixtureImagePath(name, meta),
                  cmPerPixel: _fixtureCmPerPixel(meta),
                );
                final features = envelope['features'] as Map<String, dynamic>?;
                if (features == null || !golden.containsKey('features')) {
                  // Fixtures with no reference / no scale (e.g. 05, 06, 08, 09) never
                  // reach construction+features -- nothing to pin or compare.
                  markTestSkipped(
                    'features did not run for $name on this fixture -- nothing to pin',
                  );
                  return;
                }
                // AGENTS.md rule 2, native side: family and order must equal the
                // manifest-declared feature family, never a hardcoded literal.
                final declared = _readFeatureOrderAsset();
                expect(
                  features['family'],
                  declared['feature_family'],
                  reason:
                      'features.family must equal the manifest-declared family',
                );
                expect(
                  features['order'],
                  declared['features'],
                  reason:
                      'features.order must equal feature_order.json exactly',
                );
                // Recorded, not papered over (finding 6): this fixture's features are
                // "provisional" on a passing run, and that is the observed truth (task 3's
                // golden carries a copy of that same observed value), not a bug this test
                // should silently accept or hide by not asserting it at all.
                final observedStatus =
                    ((meta['observed_phase4']
                            as Map<String, dynamic>)['envelope']
                        as Map<String, dynamic>)['features']['status'];
                expect(
                  features['status'],
                  observedStatus,
                  reason:
                      'features.status changed from what round 18 observed ($observedStatus) '
                      '-- investigate before accepting silently',
                );

                final weight = envelope['weight'] as Map<String, dynamic>?;
                if (weight == null || !golden.containsKey('weight')) {
                  markTestSkipped(
                    'weight did not run for $name on this fixture -- nothing to compare',
                  );
                  return;
                }
                expect(
                  weight['status'],
                  'ok',
                  reason: 'weight branch must reach a status for $name',
                );
                final expectedKg =
                    (golden['weight'] as Map<String, dynamic>)['estimated_kg']
                        as num;
                final actualKg = weight['estimated_kg'] as num;
                expect(
                  _absClose(expectedKg, actualKg, _tol('weight_kg_abs')),
                  isTrue,
                  reason:
                      'weight.estimated_kg mismatch for $name: expected=$expectedKg '
                      'actual=$actualKg (abs tol ${_tol('weight_kg_abs')}). This '
                      'measures native-vs-Python agreement on IDENTICAL feature input, '
                      'not accuracy: the manifest marks estimated_kg\'s stability as '
                      '"temporary" and the regressor cannot predict below ~73 kg '
                      '(finding 7) -- a passing run says nothing about correctness '
                      'against a scale, only that the two onnxruntime embeddings of '
                      'the shipped xgboost.onnx agree on the same input.',
                );
            }
          },
        );
      });
    }

    test(
      'segmentation mask + confidence parity against Python reference',
      () {},
      skip:
          'BLOCKED, not a stale placeholder: no independent Python segmentation oracle '
          'exists in this repo (the training-time `src/` package WeightEstimator needs is '
          'not present, only the deployed C++ port under model_and_cutter/ is; a from-'
          'scratch Python YOLO postprocessor would be a second unverified implementation '
          'with nothing to check it against). The real fix is native-side mask export '
          '(docs/metrics-phase/5-parity-tests.md subphase 5.1), not this test. Do not '
          'un-skip by writing a Python YOLO reimplementation for this test alone.',
    );

    test(
      'chen16 feature extraction parity (native vs Python) over ground-truth masks',
      () async {
        // Same opt-in gate as NativeHarness.load() -- this test drives a native CLI
        // directly rather than through the harness, so it must not run 500 subprocess
        // launches on a machine that has not opted into native-backed tests, even if a
        // stale CLI binary happens to be present from an earlier build.
        if (Platform.environment['INSTAHAM_NATIVE_TESTS'] != '1') {
          markTestSkipped(
            'INSTAHAM_NATIVE_TESTS not set to 1 -- native harness opt-in gate is off',
          );
          return;
        }
        final cliCandidates = [
          'build/windows-host/test/Release/chen16_feature_gate_cli.exe',
          'packages/instaham_ml_ffi/src/build/host/test/chen16_feature_gate_cli.exe',
          'packages/instaham_ml_ffi/build/host/src/test/chen16_feature_gate_cli.exe',
        ];
        final cliRelative = cliCandidates.firstWhere(
          (p) => File(p).existsSync(),
          orElse: () => '',
        );
        if (cliRelative.isEmpty) {
          markTestSkipped(
            'chen16_feature_gate_cli not built -- run the host ctest build first '
            '(INSTAHAM_ML_BUILD_TESTS=ON); see docs/metrics-plan.md phase 1',
          );
          return;
        }
        // Process.run needs an absolute path here -- a relative one intermittently
        // failed to launch with "the system cannot find the file specified" even though
        // File(cliRelative).existsSync() (above) confirmed it resolves fine for file I/O.
        final cli = File(cliRelative).absolute.path;
        // Committed golden fallback (docs/metrics-phase/5-parity-tests.md task 7's
        // documented fallback, taken deliberately rather than as a last resort): an
        // earlier version of this test drove `python -m
        // ML.parity.chen16_feature_port_gate` as a live subprocess from Dart, over the
        // full 500-mask sample. `Process.run('python', ...)` was found to resolve a
        // working but MUCH slower interpreter path than the same command run directly
        // (a >60s run vs ~4s from a shell), tripping flutter_test's per-test timeout
        // intermittently -- exactly the "fragile enough that it ships with a fallback"
        // risk the phase document called out in advance. This version instead reads a
        // PYTHON-ONLY golden committed at test/fixtures/parity/chen16_python_golden.json
        // (ML/parity/chen16_feature_port_gate.py --emit-python-golden) and drives ONLY
        // the native CLI directly from Dart -- no Python subprocess at test time, so
        // this environment issue cannot recur here. Regenerate the golden with:
        //   python -m ML.parity.chen16_feature_port_gate \
        //     --emit-python-golden test/fixtures/parity/chen16_python_golden.json \
        //     --limit 500
        // after any change to CHEN16_NOHEIGHT, extract_chen16_features, or the mask
        // corpus. The wider, fully live C++-vs-Python comparison (both sides run fresh)
        // stays available as `python -m ML.parity.chen16_feature_port_gate --limit
        // 3394`, run manually -- it is not gated on `flutter test` at all.
        final goldenFile = File(
          'test/fixtures/parity/chen16_python_golden.json',
        );
        if (!goldenFile.existsSync()) {
          markTestSkipped(
            "${goldenFile.path} not found -- generate it first (see this test's own "
            'comment for the command)',
          );
          return;
        }
        final golden =
            jsonDecode(goldenFile.readAsStringSync()) as Map<String, dynamic>;
        final order = (_readFeatureOrderAsset()['features'] as List)
            .cast<String>();
        final chen16Exact = (_tolerances['chen16_exact'] as List)
            .cast<String>()
            .toSet();
        final chen16RelTight = (_tolerances['chen16_rel_tight'] as List)
            .cast<String>()
            .toSet();
        final relTightTol = (_tolerances['chen16_rel_tight_tol'] as num)
            .toDouble();
        final relLooseTol = (_tolerances['chen16_rel_loose_tol'] as num)
            .toDouble();

        var checked = 0;
        final mismatches = <String>[];
        for (final entry in golden.entries) {
          final maskPath = entry.key;
          final expected = entry.value as Map<String, dynamic>?;
          if (expected == null) continue; // both sides agree: mask unusable
          if (!File(maskPath).existsSync()) {
            continue; // corpus not present on this machine
          }
          final result = await Process.run(cli, [maskPath]);
          final lines = (result.stdout as String)
              .split('\n')
              .map((l) => l.trim())
              .where((l) => l.isNotEmpty)
              .toList();
          final line = lines.isEmpty ? '' : lines.last;
          if (line == 'invalid' || line.isEmpty) {
            mismatches.add(
              '$maskPath: cpp says invalid, python golden has values',
            );
            continue;
          }
          final parts = line.split(',');
          if (parts.first != 'valid' || parts.length != order.length + 1) {
            mismatches.add('$maskPath: unexpected CLI output $line');
            continue;
          }
          checked++;
          for (var i = 0; i < order.length; i++) {
            final name = order[i];
            final ev = expected[name] as num;
            final av = double.parse(parts[i + 1]);
            if (chen16Exact.contains(name)) {
              if (ev.toDouble() != av) {
                mismatches.add(
                  '$maskPath: $name exact mismatch expected=$ev actual=$av',
                );
              }
              continue;
            }
            final tol = chen16RelTight.contains(name)
                ? relTightTol
                : relLooseTol;
            final denom = ev.abs() < 1e-9 ? 1e-9 : ev.abs();
            final rel = (ev.toDouble() - av).abs() / denom;
            if (rel > tol) {
              mismatches.add(
                '$maskPath: $name rel ${rel.toStringAsExponential(2)} > $tol '
                '(expected=$ev actual=$av)',
              );
            }
          }
        }

        expect(
          checked,
          greaterThan(0),
          reason:
              'no masks from the golden were found on this machine -- is '
              'Instaham/PIGRGB-Weight/MASK_3394 present?',
        );
        expect(
          mismatches,
          isEmpty,
          reason:
              'chen16 feature port gate: $checked masks checked, '
              '${mismatches.length} mismatches:\n${mismatches.take(50).join('\n')}',
        );
      },
      // 500 sequential native CLI subprocess launches comfortably exceed
      // flutter_test's default 30s per-test timeout (observed ~60-90s on this
      // machine). This is CPU/process-launch time, not a hang -- widen rather than
      // shrink the sample if this still trips on slower hardware.
      timeout: const Timeout(Duration(minutes: 3)),
    );
  });
}
